      REAL FUNCTION duration(XDUMMY)
*********************************************************
*                                                       *
* This file was generated by HUWFUN.                    *
*                                                       *
*********************************************************
*
*     Ntuple Id:      100  
*     Ntuple Title:   GRAS
*     Creation:       12/07/95 12.15.13
*
*********************************************************
*
      LOGICAL         CHAIN
      CHARACTER*128   CFILE
      INTEGER IDNEVT,NCHEVT,ICHEVT
      REAL VIDN1,VIDN2,VIDN3,VIDN(10)
*
      COMMON /PAWIDN/ IDNEVT,VIDN1,VIDN2,VIDN3,VIDN
      COMMON /PAWCHN/ CHAIN, NCHEVT, ICHEVT
      COMMON /PAWCHC/ CFILE
*
*--   Ntuple Variable Declarations
*
      REAL t10azwidth,t10width,t10length,t10distance,t10sinalpha,t10miss
     + ,t10xcentr,t10ycentr,t10phi,t10totsig,t10max1,t10loc1,t10max2
     + ,t10loc2,t10max3,t10loc3,t10rmax1,t10rloc1,t10x1,t10y1,t10rmax2
     + ,t10rloc2,t10x2,t10y2,t10hadron,t10nb2,t10nb3,t10npicture
     + ,t10asymm,t10veto,t10el,t10frac2,t10maxsep,t10xgam,t10ygam
     + ,t10gain,t10arc,t10muon
      DOUBLE PRECISION t10utc,t10deltat,t10livetime,t10phase
      LOGICAL t10ipv,t10tiv
*
      COMMON /PAWCR4/ t10ipv,t10azwidth,t10width,t10length,t10distance
     + ,t10sinalpha,t10miss,t10xcentr,t10ycentr,t10phi,t10totsig,t10max1
     + ,t10loc1,t10max2,t10loc2,t10max3,t10loc3,t10rmax1,t10rloc1,t10x1
     + ,t10y1,t10rmax2,t10rloc2,t10x2,t10y2,t10hadron,t10nb2,t10nb3
     + ,t10npicture,t10asymm,t10veto,t10el,t10frac2,t10maxsep,t10xgam
     + ,t10ygam,t10gain,t10arc,t10muon,t10tiv
      COMMON /PAWCR8/ t10utc,t10deltat,t10livetime,t10phase
*
*
*--   Enter user code here
*
      vector tdur
*
      tdur(1) = t10livetime

      END
