      REAL FUNCTION durations(mode)
*********************************************************
*                                                       *
* This file was generated by HUWFUN.                    *
*                                                       *
*********************************************************
*
*     Ntuple Id:      100  
*     Ntuple Title:   GRAS
*     Creation:       29/06/95 18.31.42
*
*********************************************************
*
      LOGICAL         CHAIN
      CHARACTER*128   CFILE
      INTEGER IDNEVT,NCHEVT,ICHEVT
      REAL VIDN1,VIDN2,VIDN3,VIDN(10)
*
      COMMON /PAWIDN/ IDNEVT,VIDN1,VIDN2,VIDN3,VIDN
      COMMON /PAWCHN/ CHAIN, NCHEVT, ICHEVT
      COMMON /PAWCHC/ CFILE
*
*--   Ntuple Variable Declarations
*
      REAL t10azwidth,t10width,t10length,t10distance,t10sinalpha,t10miss
     + ,t10xcentr,t10ycentr,t10phi,t10totsig,t10max1,t10loc1,t10max2
     + ,t10loc2,t10max3,t10loc3,t10rmax1,t10rloc1,t10x1,t10y1,t10rmax2
     + ,t10rloc2,t10x2,t10y2,t10hadron,t10nb2,t10nb3,t10npicture
     + ,t10asymm,t10veto,t10el,t10frac2,t10maxsep,t10xgam,t10ygam
     + ,t10gain,t10arc,t10muon
      DOUBLE PRECISION t10utc,t10deltat,t10livetime,t10phase
      LOGICAL t10ipv,t10tiv
*
      COMMON /PAWCR4/ t10ipv,t10azwidth,t10width,t10length,t10distance
     + ,t10sinalpha,t10miss,t10xcentr,t10ycentr,t10phi,t10totsig,t10max1
     + ,t10loc1,t10max2,t10loc2,t10max3,t10loc3,t10rmax1,t10rloc1,t10x1
     + ,t10y1,t10rmax2,t10rloc2,t10x2,t10y2,t10hadron,t10nb2,t10nb3
     + ,t10npicture,t10asymm,t10veto,t10el,t10frac2,t10maxsep,t10xgam
     + ,t10ygam,t10gain,t10arc,t10muon,t10tiv
      COMMON /PAWCR8/ t10utc,t10deltat,t10livetime,t10phase
*

*
*--   Enter user code here
*
      vector durs
      integer i
      real lasttime,mode
      character*27 mess(2)
      character*9 name

      if (idnevt.eq.1) then
         i=1
         lasttime=0.0
         mess(1)='ON data - duration of run  '
         mess(2)='OFF data - duration of run '
         name=cfile(1:9)
      else if (ichevt.eq.1) then
         durs(i)=lasttime
         write(6,70)mess(mode),i,name,durs(i)
         i=i+1
         name=cfile(1:9)
      else if (idnevt.eq.nchevt) then 
         durs(i)=t10livetime
         write(6,70)mess(mode),i,cfile(1:9),durs(i)
      endif
     
      lasttime=t10livetime

 70   format(a27,1x,i3,2x,a10,2x,f9.3,' seconds.')
*
      END






