      REAL FUNCTION qluw151(XDUMMY)
*
* Changed by JQ 970304 to use 151 camera optimum cuts
*
*********************************************************
*                                                       *
* This file was generated by HUWFUN.                    *
*                                                       *
*********************************************************
*
*     Ntuple Id:      100  
*     Ntuple Title:   GRAS
*     Creation:       12/07/95 12.15.13
*
*********************************************************
*
      LOGICAL         CHAIN
      CHARACTER*128   CFILE
      INTEGER IDNEVT,NCHEVT,ICHEVT
      REAL VIDN1,VIDN2,VIDN3,VIDN(10)
*
      COMMON /PAWIDN/ IDNEVT,VIDN1,VIDN2,VIDN3,VIDN
      COMMON /PAWCHN/ CHAIN, NCHEVT, ICHEVT
      COMMON /PAWCHC/ CFILE
*
*--   Ntuple Variable Declarations
*
      REAL t10azwidth,t10width,t10length,t10distance,t10sinalpha,t10miss
     + ,t10xcentr,t10ycentr,t10phi,t10totsig,t10max1,t10loc1,t10max2
     + ,t10loc2,t10max3,t10loc3,t10rmax1,t10rloc1,t10x1,t10y1,t10rmax2
     + ,t10rloc2,t10x2,t10y2,t10hadron,t10nb2,t10nb3,t10npicture
     + ,t10asymm,t10veto,t10el,t10frac2,t10maxsep,t10xgam,t10ygam
     + ,t10gain,t10arc,t10muon
      DOUBLE PRECISION t10utc,t10deltat,t10livetime,t10phase
      LOGICAL t10ipv,t10tiv
*
      COMMON /PAWCR4/ t10ipv,t10azwidth,t10width,t10length,t10distance
     + ,t10sinalpha,t10miss,t10xcentr,t10ycentr,t10phi,t10totsig,t10max1
     + ,t10loc1,t10max2,t10loc2,t10max3,t10loc3,t10rmax1,t10rloc1,t10x1
     + ,t10y1,t10rmax2,t10rloc2,t10x2,t10y2,t10hadron,t10nb2,t10nb3
     + ,t10npicture,t10asymm,t10veto,t10el,t10frac2,t10maxsep,t10xgam
     + ,t10ygam,t10gain,t10arc,t10muon,t10tiv
      COMMON /PAWCR8/ t10utc,t10deltat,t10livetime,t10phase
*
*
*--   Enter user code here
*
      logical cuts(13)
      logical supercuts
      real ftime
      real lendsize
*
      cuts(1)=(t10distance.gt.0.51).and.(t10distance.lt.1.17)  
      cuts(2)=(t10width.gt.0.073).and.(t10width.lt.0.160)  
      cuts(3)=(t10length.gt.0.16).and.(t10length.lt.0.33) 
      cuts(4)=(t10max1.gt.95.).and.(t10max2.gt.45.)
     +  .and.(t10totsig.gt.00.)  
      cuts(5)= t10sinalpha.lt.0.26
      cuts(6)=(t10max1.gt.95).and.(t10max2.gt.45)
      cuts(9)=t10nb2.gt.0.5            
      cuts(10)=t10nb3.gt.0.5
      cuts(11)=t10livetime.lt.1620.0
      cuts(12)=(t10sinalpha.gt.0.342).and.(t10sinalpha.lt.1.0)
      cuts(13)=(t10max2-t10max3).gt.20.0
*
      supercuts=cuts(1).and.cuts(2).and.cuts(3).and.cuts(4)
     +  .and.cuts(5)
*      
      if((t10rloc2.lt.92.0).and.cuts(13)) then
        call HFILL(10,t10rmax2,0.,1.)
      endif
      if(cuts(13)) then
        call HFILL(15,t10rloc2,0.,1.)
        call HFILL(15,t10rloc1,0.,1.)
      endif
      if(supercuts) then
        if(cuts(13)) then
          call HFILL(17,t10rloc2,0.,1.)
          call HFILL(17,t10rloc1,0.,1.)
        endif
        call HFILL(20,t10x2,t10y2,1.)
        call HFILL(20,t10x1,t10y1,1.)
        call HFILL(40,t10npicture,0.,1.)
        call HFILL(75,t10hadron,0.,1.)
        call HFILL(82,t10gain,0.,1.)
        call HFILL(95,t10nb3+t10nb2+1.0,0.,1.)
      endif
      ftime=t10phase
      call HFILL(25,ftime,0.,1.) 
      if(cuts(1).and.cuts(2).and.cuts(3).and.cuts(4).and.
     +  cuts(12)) then
        call HFILL(30,ftime,0.,1.)
      endif
      ftime=t10deltat
      call HFILL(50,ftime,0.,1.)
      call HFILL(55,ftime,0.,1.)
      call HFILL(61,t10length,0.,1.)
      if(cuts(1).and.cuts(2).and.cuts(4).and.cuts(5)) then
        call HFILL(62,t10length,0.,1.) 
      endif
      call HFILL(63,t10width,0.,1.)
      if(cuts(1).and.cuts(3).and.cuts(4).and.cuts(5)) then
        call HFILL(64,t10width,0.,1.)
      endif
      call HFILL(65,t10distance,0.,1.)
      if(cuts(2).and.cuts(3).and.cuts(4).and.cuts(5)) then
        call HFILL(66,t10distance,0.,1.)
      endif
      if(cuts(2).and.cuts(3).and.cuts(4)) then
        call HFILL(99,t10xgam,t10ygam,1.)
      endif
* 
      call HFILL(67,t10totsig,0.,1.)
      if(cuts(1).and.cuts(2).and.cuts(3).and.cuts(5)) then
        call HFILL(68,t10totsig,0.,1.)
      endif
      call HFILL(70,t10hadron,0.,1.)
      call HFILL(80,t10gain,0.,1.)
      if(t10muon.lt.0.1) then
        call HFILL(85,t10gain,0.,1.)
      end if
      if(t10totsig.gt.0.) then
        lendsize = t10length/t10totsig
        call HFILL(86,lendsize,0.,1.)
        if(supercuts) then
          call HFILL(87,lendsize,0.,1.)
        endif
        if(t10muon.lt.0.1) then
          call HFILL(88,lendsize,0.,1.)
        endif
      endif
      call HFILL(89,t10veto,0.,1.)
      call HFILL(90,t10nb3+t10nb2+1.0,0.,1.)
*        
*     qluw = 1.
*
      END
